### ISSUE TITLE
Test files not being found

### ISSUE THREAD

**Issue by DanAtShenTech** [jakeharding/django-jasmine#17]
I have urls set up:
`url(r'^jtests/', include('django_jasmine.urls')),`

and the following in settings.py:
`STATIC_URL = '/static/'`
`BASE_DIR = os.path.dirname(os.path.dirname(__file__))`
`JASMINE_TEST_DIRECTORY = os.path.join(BASE_DIR, '../tests_jasmine')`
(For now the tests are in a directory that is one level above the BASE_DIR.)

The following shows the incorrect script tag that appears in index.html:
![image](https://user-images.githubusercontent.com/7819909/27742704-99241bae-5d87-11e7-8ef2-e0a015550bd8.png)

Since your instructions say that the tests are to be inside a folder named 'spec', which is to be inside the JASMINE_TEST_DIRECTORY, I don't understand why /spec is not part of the above url for the script tag (not to mention the fact that the urls prefix [in my case jtests] is also included in the url).  Also, if the tests can be located in any folder that is designated by JASMINE_TEST_DIRECTORY, then why do the instructions say that the STATIC_URL must be defined in settings?  I can see that it could be a problem having the tests located one level above the BASE_DIR, but it seems like the urls qualifier shouldn't be in the script tag. 
 Thank you.

**Comment by DanAtShenTech** [comment]
Update:  I looked at the urls file and discovered that you had sub-urls.  The above error was coming up when I went to http://mydomain/jtests/.  I have moved the tests_jasmine folder into my static folder and am now entering the url http://mydomain/jtests/tests/ as the url in the browser.  STATIC_URL is defined correctly.  This is an existing app that is working fine.  I am getting this error:  "/static/tests_jasmine/spec" does not exist.  Even if I put a specific filename after the /jtests/tests/ it gives an error that the filename can't be found.  I guess I'm doing something wrong with the urls, but I just can't see it.  Just a suggestion - perhaps redirect the main designator (in my case 'jtests')  url to go to the 'tests' sub-url.

**Comment by jakeharding** [comment]
Django serves static files by collecting all the static files from installed packages and serves them from a single folder via the settings.STATIC_URL so you won't tests_jasmine/spec in the url in the template.  Your JASMINE_TEST_DIRECTORY will need be a subfolder of the static folder in your application so Django will know to include them with the other static files.

**Comment by DanAtShenTech** [comment]
Did you see my second comment above yet?  After my first comment I tried moving my tests_jasmine folder into the static folder and setting `JASMINE_TEST_DIRECTORY = os.path.join(STATIC_URL, 'tests_jasmine')`.  It is giving me this message:  "/static/tests_jasmine/spec" does not exist.  It's like it's not prepending the base url (in my case localhost) before it looks for the static folder.

**Comment by jakeharding** [comment]
I did see your comment. ```JASMINE_TEST_DIRECTORY = os.path.join(BASE__DIR, 'tests_jasmine')``` is not be a subdirectory of your static file folder in a standard Django set up. (assuming the double underscore in ```BASE__DIR``` is typo).  You should also be able to navigate to the /jtests/ and see your results (without the extra /tests/).  You mention your app is working fine.  Is django_jasmine new to your app?

**Comment by DanielSwain** [comment]
Thanks very much.  I think I have it now.  Yes, django_jasmine is new to our app.  I'm now seeing results that are failing, but I'm also getting this error:  _Uncaught TypeError: Cannot read property 'env' of undefined
    at new HtmlReporter_.  Could that error be caused by the failing tests?  When I set breakpoints in my test file (in Chrome Developer Tools) I'm seeing this error come back before anything.  The syntax of my test file matches Jasmine's expected syntax:

    describe("description", function ( ) {
        it("does something", function ( ) {
           expect( ).xxx( )
        })
    })

**Comment by jakeharding** [comment]
Nope that is an error thrown by Jasmine and it won't have an affect on the outcome of your tests.  Do you have any suggestions that would help prevent a situation like this or improve anything?

**Comment by DanielSwain** [comment]
I don't see anything yet as far as preventing this situation, but I do have one question/suggestion on another item:  would you consider just using the standard Jasmine setup - perhaps the folder structure (spec > javascripts > support) but more importantly, the jasmine.yml file?  Currently with your 'files.json' I can't specify a wildcard (for example js/*.js).  Is there an advantage to using your files.json over the jasmine.yml?  Also, of course, the jasmine.yml file has a lot more parameters than does files.json.  I'm just learning Jasmine testing here, so maybe this question/suggestion is not a good one.  It's just that when I saw that Pivotal Labs has an installation available through `pip install jasmine` and that it uses their standard yml file, I was inclined to want to use that over django_jasmine because it seemed like dj was adding extra/changing setup parameters (the yml file specifically) that weren't necessary.  But I decided to go ahead and try d_j when I had a bit of trouble getting the Pivotal Labs installation to work.

**Comment by DanielSwain** [comment]
Also, with the single JASMINE_TEST_DIRECTORY variable, how would that handle the situation where (my preference) tests are stored in the individual app folders?

**Comment by jakeharding** [comment]
Good suggestion.  The files.json method was implemented when I inherited the project so I didn't change it, but it is definitely worth looking into using the jasmine.yml.  Maybe this will solve the problem of storing the test files as you prefer (it is my preference as well).  Thank you for your suggestions and I will open new issues for them. I see two issues one for the jasmine.yml vs files.json and one for the error being thrown by jasmine in the index.html.  Closing this one as solved, but please feel free to open another should you have any problems. 😁

**Comment by DanielSwain** [comment]
Thanks very much.  I'm now watching the repo for future upates.
