### ISSUE TITLE
Add csrf_token to base.html

### ISSUE THREAD

**Issue by DanielSwain** [jakeharding/django-jasmine#21]
Easy enough for us to do, but also easy for you to do to in order to establish this as  a default situation.  I know that Django's testing framework [disables the csrf checking](https://docs.djangoproject.com/en/1.11/topics/testing/tools/#overview-and-a-quick-example), so would this be legitimate in a testing environment?

**Comment by jakeharding** [comment]
The [csrf_token](https://docs.djangoproject.com/en/1.11/ref/csrf/) is designed to be part of a form and submitted as part of a post request so I don't see how it would fit into the base.html.  Could you provide an example of how you are using it?

**Comment by DanielSwain** [comment]
I was just thinking that if the tests are testing POSTs to endpoints, then a CSRF token would be necessary. 
 I'm still learning about testing in Django, so maybe using Jasmine in this way isn't the best way to test endpoints.  Please close this if there is nothing more to be said here.

**Comment by jakeharding** [comment]
Closing this for now.
